### ISSUE TITLE
Have you seen PyLaTeX?

### ISSUE THREAD

**Issue by JelteF** [mbr/latex#1]
I happened to stumble on this package through a Pypi search for my own project [PyLaTeX](https://github.com/JelteF/PyLaTeX). Did you see it before creating your own similar library? If so what were you missing and couldn't it have been added with a pull request?

**Comment by mbr** [comment]
First, I am sorry about the name clash. I've only semi-named it "pylatex",
because having "LaTeX" as the documentation title seemd a bit grand.

To answer your question, here's how it went:

I often write software that generates LaTeX documents and requires them to
be compiled. For me that means handwritten LaTeX templates, since the
applications were quite varied: Invoices, letters using KOMAScript (very
popular among german LaTeX user) and some completely different things [1]_.

Two components were required:

* Configuring Jinja2 (my template engine of choice) for better use with
LaTeX.
* Compiling LaTex documents to PDF without making a mess.

For compiling, I would write SConstruct [2]_ files, as the built-in LaTeX
builder worked well. That still left a lot of temporary files and I did not
want to run a ``clean`` just to see what files I have. While looking for a
solution to being able to build PDF files from ``.latex`` ones, I ran
across `tex <https://pypi.python.org/pypi/tex>`_. It roughly did what I
wanted, but I couldn't extend it well, because it has been superseded by
`texcaller <https://vog.github.io/texcaller/>`_, which might as well not
exist because it is not PyPI-installable.

The second component just came in after I noticed I had written (to be
honest, it was closer to copy & pasting snippets) the same Jinja2
``Environment`` configuration two-and-a-half times.

That's why I created the library. As always, I did search PyPI for a bit;
if you type in ``latex`` into the search, it also lists your package.
However, in the short description it doesn't explicitly mention being able
to build LaTeX documents and the main focus seems to be on generating LaTeX
source - which I write using templates!

I will freely admit that I did not look into it, as I was looking for a
library to *build* documents, not generate them.

If I looked at it now, it would seem your library is trying to solve a
different problem than mine. Here's why I would *personally* choose mine
right now over yours:

Functional differences
~~~~~~~~~~~~~~~~

* It does not leave a mess because it builds in a temporary directory.
There's more possible temporary files than the 4 extensions in
https://github.com/JelteF/PyLaTeX/blob/master/pylatex/document.py#L131
* It tries a little harder to correctly build the file. You usually need to
rerun latex more than once, especially if stuff like BibTeX is involved.
* I haven't run it, but by looking at it, I would think that building hangs
if an error is present in the latex document (it's missing stuff like
``-interaction=batchmode``). See also the other command-line flags.
* There's no obvious, straight-forward way to take an input LaTeX file and
get a PDF file as output.


Problems regardless of functionality
~~~~~~~~~~~~~~~~~~~~~~~~~~

* You're open to accidental or malicious shell injection. What happens if
``filename`` ends up being ``; rm -rf /; #`` ? I'd be extra careful if I
used the lib to render user-submitted LaTeX files.
* Your ``rm_tmp`` is a really bad idea. It does not work at all with
packages installed in a read-only environment. It's also not called if
exceptions occur and so on. You may want to give ``tempfile`` and
``tempdir`` a look.
* You're using ``.split()`` instead of ``os.path.split``, although that may
be minor issue, since I am not sure ``pdflatex`` is runnable on Windows.
* You're focused (according to the docs) on Python 3. I usually write for
Python 2.7 and port to Python 3.3+ if possible, which I find a much saner
approach. Going into detail there is a bit much right here though.


That's at first glance. I am sorry if I misread some code.

All in all, the functional overlap of ``latex`` and ``PyLaTeX`` seems to be
only in the ``generate_pdf()`` method of ``PyLaTeX``. As that is
``latex``'s only job, it does it a little more thoroughly. But honestly,
it's just a way for me to reuse code I've written twice, with an excuse for
documentation slapped on. It's nice that the name ``latex`` was free though
=).

I appreciate the effort to consolidate packages, it's something that does
not happen often enough. Yours is much larger in scope than mine. If you
end up replacing ``generate_pdf()`` with a call to ``build_pdf()`` let me
know, I'll try to clean up ``latex`` some more.


.. [1] None of the projects are open source and reside mostly on my private
machines. Sorry.
.. [2] SCons is still one of the least bad build tools (they all suck), see
http://scons.org

**Comment by JelteF** [comment]
Thanks for the thorough response. You are indeed right that the actual compiling of the LaTeX code isn't a main goal of the project. It's main goal is generating correct LaTeX files that can be compiled, and because you probably want to compile it as well it is one of the features. So it's a bit hacked in. Also, the building is mainly focussed on Linux, since I don't use PyLaTeX on Windows and Travis doesn't have Windows support yet.

You're compile function seems way better than mine, so it would probably good to let my library depend on yours for the building of the actual pdf. I think that would be easier than somehow merging the libraries with an indeed quite different goal. 

Maybe I'll also make an interface to access the Jinja template stuff, since that might be usefull as well. The way I use my library when I only need a snippet generated is with the `\input` command. 

BTW your project doesn't have a LICENSE file yet. You should probably add one.

**Comment by mbr** [comment]
Pull LICENSE, also largely rewrote the build part. Have a look at 0.5.2.

Closing this issue.
